= ReVector Demo

ifdef::env-github[]
image:https://img.shields.io/badge/release-standard%20version-brightgreen.svg[Standard Version, link=https://github.com/conventional-changelog/standard-version]
endif::[]

== About

Demo for ReVector components. It would be spiffy to integrate this into the revector project itself. Sadly there are issues with making the build systems play nice.

== Use

@todo

== Contributing

@todo

=== Building

Create the local environment file (./src/environments/environment.local.ts) and add your firebase config to it:

[source, javascript]
/**
 * Environment that does not get committed to source control
 */
export const noCommitEnvironment = {
  firebaseConfig: {
    apiKey: "$KEY",
    authDomain: "$DOMAIN.firebaseapp.com",
    databaseURL: "https://$DOMAIN.firebaseio.com",
    storageBucket: "$DOMAIN.appspot.com",
  }
};

Then:

[source, bash]
npm install
ng serve

You'll need to install angular-cli globally if you haven't already. Or (as I prefer to do) create an alias:

[source, bash]
echo alias ng="./node_modules/.bin/ng" >> ~/.bash_aliases
source ~/.bash_aliases

=== Running unit tests

@todo

=== Running end-to-end tests

@todo

